### ISSUE TITLE
Ichor applied by `Weapon Imbue: Ichor` is not synced across clients in PvP

### ISSUE THREAD

**Issue by drunderscore** [Pryaxis/Terraria#9]
### Is there an existing issue for this?

- [X] I have searched this repository for an existing issue matching this description, and none exists. I understand this issue will be closed as a duplicate if this is not the case.

### Tested platforms

- [ ] Windows
- [ ] OSX
- [X] Linux

### Reproduction steps (if known)

- Be under the effect of Weapon Imbue: Ichor (by drinking a Flask of Ichor)
- Hit another player in PvP with a melee weapon
- Observe desync (the attacker believes you have ichor, but the attacked player does not.

### Additional information

The attacker implicitly applies the debuff -- other clients are probably meant to do the same.
TShock can patch this by having the server tell other clients to apply Ichor to the attacked player when the attacker has Weapon Imbue: Ichor.

**Comment by punchready** [comment]
All buffs applied in `Player.StatusToPlayerPvP` that do not have `silent` explicitly set to false are not synced in pvp. This is so grotesk that it might actually be intentional, somehow? Especially the Brand of the Inferno sticks out as the only `AddBuff` call in a switch statement that does not set `silent` to `false`, i cannot imagine anybody writing this code and not noticing.

**Comment by drunderscore** [comment]
This was resolved in 1.4.4
